apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: dev-webapp
spec:
  type: NodePort
  selector:
    app: apache-webapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
